var en = {
	o:			"O",
	h:			"H",
	l:			"L",
	c:			"C",
	v:			"V",
	mp:			"MP",
	mc:			"MC",
	mpc:		"MP(C)",
	ar:			"AR",
	modal_point:"Modal Point",
    support:	"S",
    resistance:	"R",
    latest_mp:	"Latest MP",
    bull:		"Bull",
    bear:		"Bear",
    chart:		"Chart",
    
    Daily:		"Daily",
    Weekly:		"Weekly",
    Monthly:	"Monthly",
    Min1:		"1-min",
    Min5:		"5-min",
    Min10:		"10-min",
    Min15:		"15-min",
    Min30:		"30-min",
    Hour1:		"1-hour",
    Hour2:		"2-hour",
    Hour4:		"4-hour",
    
    SMA:		"SMA",
    Boll:		"Boll",
    EMA:		"EMA",
    SAR:		"SAR",
    Ichimoku:	"Ichimoku",
    WMA:		"WMA",
    MAE:		"MAE",
    KC:			"KC",
    
    VOLUME:		"Volume",
    RSI:		"RSI",
    MACD:		"MACD",
    STC:		"Stochastic",
    MOM:		"Momentum",
    PCTR:		"PercentageR",
    OBV:		"OBV",
    MC:			"Modal Count",
    ROC:		"ROC",
    ADX:		"ADX",
    MFI:		"MFI",
    VOLA:		"Volatility",
    VOLP:		"Volume+",
    VAO:		"VAO",
    CCI:		"CCI",
    ATR:		"ATR",

};

var tc = {
	o:			"開",
	h:			"高",
	l:			"低",
	c:			"收",
	v:			"成",
	mp:			"聚焦點",
	mc:			"聚焦量",
	mpc:		"聚焦點(量)",
	ar:			"活躍區",
	modal_point:"聚焦點",
    support:	"支持",
    resistance:	"阻力",
    latest_mp:	"最新聚焦點",
    bull:		"牛證",
    bear:		"熊證",
    chart:		"圖表",

    Daily:		"日圖",
    Weekly:		"週圖",
    Monthly:	"月圖",
    Min1:		"1分鐘",
    Min5:		"5分鐘",
    Min10:		"10分鐘",
    Min15:		"15分鐘",
    Min30:		"30分鐘",
    Hour1:		"1小時",
    Hour2:		"2小時",
    Hour4:		"4小時",

    SMA:		"SMA",
    Boll:		"保力加通道",
    EMA:		"EMA",
    SAR:		"拋物線",
    Ichimoku:	"一目均衡圖",
    WMA:		"WMA",
    MAE:		"MAE",
    KC:			"KC",

    VOLUME:		"成交量",
    RSI:		"相對強弱指數(RSI)",
    MACD:		"移動平均匯聚背馳指標(MACD)",
    STC:		"隨機指數(STC)",
    MOM:		"動力指標(MOM)",
    PCTR:		"威廉指標R",
    OBV:		"成交量平衡指數(OBV)",
    MC:			"聚焦量",
    ROC:		"變動速度指標(ROC)",
    ADX:		"動向指數(ADX)",
    MFI:		"資金流向指數(MFI)",
    VOLA:		"波動率",
    VOLP:		"成交量+(VOLP)",
    VAO:		"成交量累積指標(VAO)",
    CCI:		"順勢指標(CCI)",
    ATR:		"平均真正波幅(ATR)",
};

var sc = {
	o:			"开",
	h:			"高",
	l:			"低",
	c:			"收",
	v:			"成",
	mp:			"聚集点",
	mc:			"聚焦量",
	mpc:		"聚焦点(量)",
	ar:			"活跃区",
	modal_point:"聚焦点",
	support:	"支持",
	resistance:	"阻力",
	latest_mp:	"最新聚焦点",
    bull:		"牛证",
    bear:		"熊证",
    chart:		"图表",

    Daily:		"日图",
    Weekly:		"周图",
    Monthly:	"月图",
    Min1:		"1分钟",
    Min5:		"5分钟",
    Min10:		"10分钟",
    Min15:		"15分钟",
    Min30:		"30分钟",
    Hour1:		"1小时",
    Hour2:		"2小时",
    Hour4:		"4小时",

    SMA:		"SMA",
    Boll:		"保力加通道",
    EMA:		"EMA",
    SAR:		"拋物线",
    Ichimoku:	"一目均衡图",
    WMA:		"WMA",
    MAE:		"MAE",
    KC:			"KC",

    VOLUME:		"成交量",
    RSI:		"相对强弱指数(RSI)",
    MACD:		"移动平均汇聚背驰指标(MACD)",
    STC:		"随机指数(STC)",
    MOM:		"动力指标(MOM)",
    PCTR:		"威廉指标R",
    OBV:		"成交量平衡指数(OBV)",
    MC:			"聚焦量",
    ROC:		"变动速度指标(ROC)",
    ADX:		"动向指数(ADX)",
    MFI:		"资金流向指数(MFI)",
    VOLA:		"波动率",
    VOLP:		"成交量+(VOLP)",
    VAO:		"成交量累积指标(VAO)",
    CCI:		"顺势指标(CCI)",
    ATR:		"平均真正波幅(ATR)",
};